spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
